// /app/blog/blogs-data.ts
export const BLOGS = [
  {
    id: 1,
    title: "Romi's Journey: From Accident to Inspiration",
    description: "How a car accident in 2020 couldn't stop Romi's spirit. His story of resilience and daily physiotherapy.",
    image: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Rescue Story", "Permanent Care", "Inspiration"],
    author: "Animal Welfare Team",
    date: "2025-01-15",
    views: 892,
  },
  {
    id: 2,
    title: "The 320-Dog Feeding Challenge",
    description: "Inside our massive feeding program during campus breaks - how we ensure no animal goes hungry.",
    image: "https://images.pexels.com/photos/4498185/pexels-photo-4498185.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Feeding Program", "Campus Life", "Volunteer Work"],
    author: "Volunteer Coordinator",
    date: "2025-01-10",
    views: 654,
  },
  {
    id: 3,
    title: "Train Accident Survivor: A 6-Month Journey",
    description: "The emotional story of a young pup who survived a train accident and touched thousands of hearts.",
    image: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Emergency Rescue", "Medical Care", "Community Support"],
    author: "Emergency Response Team",
    date: "2025-01-05",
    views: 1247,
  },
  {
    id: 4,
    title: "Chedi's Final Chapter: Cancer Care with Dignity",
    description: "How we provided chemotherapy and palliative care to an elderly campus dog, ensuring his final years were filled with love.",
    image: "https://images.pexels.com/photos/1390361/pexels-photo-1390361.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Medical Care", "Elderly Animals", "Palliative Care"],
    author: "Medical Team",
    date: "2024-12-28",
    views: 743,
  },
  {
    id: 5,
    title: "From Hairless to Beautiful: Hippo's Transformation",
    description: "Months of patient treatment transformed Hippo from a sick, hairless dog to a healthy companion with a shiny coat.",
    image: "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Recovery Story", "Medical Treatment", "Before & After"],
    author: "Veterinary Team",
    date: "2024-12-20",
    views: 567,
  },
  {
    id: 6,
    title: "Building Our Permanent Shelter: The Urgent Need",
    description: "Why we desperately need a dedicated sanctuary for our growing number of elderly and disabled animals.",
    image: "https://images.pexels.com/photos/6816861/pexels-photo-6816861.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Shelter Project", "Fundraising", "Future Plans"],
    author: "Organization Leadership",
    date: "2024-12-15",
    views: 923,
  },
  {
    id: 7,
    title: "Bunti's Wheelchair Adventures",
    description: "How a specially designed wheelchair gave Bunti, paralyzed at one month old, the freedom to explore and play.",
    image: "https://images.pexels.com/photos/2023384/pexels-photo-2023384.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Disability Care", "Innovation", "Quality of Life"],
    author: "Rehabilitation Team",
    date: "2024-12-10",
    views: 445,
  },
  {
    id: 8,
    title: "Vaccination Drive 2024: Protecting 3,000+ Dogs",
    description: "Our largest vaccination campaign yet - how we protected the entire campus and surrounding community from rabies and diseases.",
    image: "https://images.pexels.com/photos/4498185/pexels-photo-4498185.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Vaccination", "Community Health", "Prevention"],
    author: "Public Health Team",
    date: "2024-12-05",
    views: 678,
  },
  {
    id: 9,
    title: "Simba's Confidence Journey",
    description: "From a malnourished, fearful puppy to one of campus's most confident and happy dogs - Simba's remarkable transformation.",
    image: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Rehabilitation", "Behavioral Recovery", "Success Story"],
    author: "Behavioral Specialist",
    date: "2024-11-30",
    views: 534,
  },
  {
    id: 10,
    title: "24/7 Emergency Response: What It Really Means",
    description: "Behind the scenes of our round-the-clock emergency hotline and the dedicated volunteers who make it possible.",
    image: "https://images.pexels.com/photos/6816861/pexels-photo-6816861.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Emergency Response", "Volunteer Life", "Behind the Scenes"],
    author: "Emergency Coordinator",
    date: "2024-11-25",
    views: 789,
  },
  {
    id: 11,
    title: "Shanti's Welcome: How She Inspires New Volunteers",
    description: "Meet Shanti, our paraplegic ambassador who welcomes every new volunteer and shows them the beauty of caring for disabled animals.",
    image: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Volunteer Training", "Inspiration", "Permanent Care"],
    author: "Volunteer Trainer",
    date: "2024-11-20",
    views: 612,
  },
  {
    id: 12,
    title: "From 2019 to 2025: Our Journey to NGO Status",
    description: "How a small group of concerned students grew into a registered NGO recognized by the West Bengal government.",
    image: "https://images.pexels.com/photos/6816861/pexels-photo-6816861.jpeg?auto=compress&cs=tinysrgb&w=600",
    tags: ["Organization History", "Milestones", "Growth"],
    author: "Founding Members",
    date: "2024-11-15",
    views: 856,
  }
];